### ISSUE TITLE
rntop runs as root contrary to best practices

### ISSUE THREAD

**Issue by drjasonharrison** [run-ai/rntop#4]
Is there any reason that the docker image for rntop leave the user as root? This is contrary to best practices for security.

A quick reading of the README and the source leads me to understand that rntop is ssh'ing to remote machines and running nvidia-smi on the remote machine. This means that you don't need root on either the local machine, remote machine, or within the container.

**Comment by rotenbergrr** [comment]
hi @drjasonharrison and thanks for reaching out!

you are 100% right that we don't need root permissions for running the container.
we can change the user to another one.
did you mean creating a new user in the Dockerfile and using it like in [this](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user) example?
or did you mean running the container with a specified non-root user id?

the only concern I have is if this new user will have read permissions to the SSH config file (i.e. `~/.ssh/config`)

**Comment by drjasonharrison** [comment]
@razrotenberg either creating a user in the docker image, or running the container with a non-root user id.

**Comment by rotenbergrr** [comment]
@drjasonharrison I looked into the direction of creating a dedicated, non-root user in the Docker image like presented [here](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user) and [here](https://www.thegeekdiary.com/run-docker-as-a-non-root-user/).

The problem is that `rntop` relies on the mounted `~/.ssh` directory for:
1. Configuration file (`~/.ssh/config`)
2. SSH keys

This directory is mounted from the host, and the permissions of the files vary per environment.

I easily simulated a scenario in which `rntop` failed to run with such a dedicated user because the mounted `~/.ssh` directory had user specific permissions.

For this reason, we _can't_ create a dedicated non-root user in the Docker image in a way that would still work in 100% of the environments.

Because this is environment specific, you can use the [`-u` flag for `docker run`](https://docs.docker.com/engine/reference/run/#user) to run the container with a user that you would create priorly.
Because you control the environment you could make sure this user has enough permissions for the `~/.ssh` directory.

Please let me know if this solves the issue for you, and thanks again for reaching out!

**Comment by rotenbergrr** [comment]
@drjasonharrison I'm closing the issue for now.
Please reopen it if you feel like my suggestion is not enough!
